name: lineups-iq
favicon: null
layout_spectrum: 0.07973811030387878
typography_spectrum: 0.07582693290896714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#51596b'
    - '#9bc90c'
    - '#fefeff'
    - '#d2d4d7'
    - '#868b94'
  brandStrength: 0.4979640766978264
  lightness: 0.15874426090158522
  saturation: 0.7433867461513728
  rhythmicContrast: 0.784703029319644
purpose: []
